use_frameworks!

target 'KeyboardNotificationsObserver_Example' do
  pod 'KeyboardNotificationsObserver', :path => '../'

  target 'KeyboardNotificationsObserver_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.1'
    pod 'Nimble', '~> 8.0'
  end
end
